security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: user
            user_checker: App\Security\UserChecker
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: homepage
                username_parameter: _username
                password_parameter: _password
            logout:
                path: /logout
                target: /

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
